version: '3.7'
services:

    app:
        build: app
        volumes:
          - ./app:/app

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
